[build]
command = "npm install && npm run build:shared && npm run build:backend"

[deploy]
startCommand = "npm run start --workspace=@webdevinterviews/backend"

[env]
# Railway will automatically set PORT
# Add your other environment variables in the dashboard:
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
# ADMIN_USER_ID (optional)