[build]
command = "./build.sh"

[deploy]
startCommand = "node packages/backend/dist/index.js"

[env]
# Railway will automatically set PORT
# Add your other environment variables in the dashboard:
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
# ADMIN_USER_ID (optional)